### ISSUE TITLE
read_ngsfilter

### ISSUE THREAD

**Issue by rongiergaetan** [metabaRfactory/metabaR#34]
I noticed, I can't upload an NGSfilter file if one or more sample have the same forward and reverse tag, because the read_ngsfilter function doesn't take into account if they are a T instead of F in the 6th column.

**Comment by lzinger** [comment]
Hi. The setting you are describing should happen (i) if you have > 1 marker or primer pair or (ii) > 1 library in your ngsfilter file. metabaR has been designed to work with one single marker and library at a time because all errors (including sequencing ones) should be specific to the marker/primer pair and library. I would suggest you to split your ngsfilter file according either to the marker/primer pair, or library. Please let us know if it works with the recommendations above. thanks!

**Comment by rongiergaetan** [comment]
I have juste one marker pair on my ngsfilter, but different tags pairs. And if I just replace the T letter by F  in the 6th column all is fonctionning. I think it's here in source code : 
          - "additional <- gsub("F @ ", "", as.vector(input$additional))"
          
there aren't the command line to take into account the "T" instead of "F".

**Comment by lzinger** [comment]
Ok I see, sorry for the misunderstanding. Just corrected the bug, will push the function shortly. Thanks for noticing and reporting the problem!
