### ISSUE TITLE
check_pcr_repl won't work if your samples names start with digits

### ISSUE THREAD

**Issue by LafontRapnouilTristan** [metabaRfactory/metabaR#50]
Hello,

first I would like to thank you guys for this amazing package!

I encountered a little problem with my data which is not major at all but thought I should report it.

It happened that I named my samples using a code starting with digits (e.g., 05_R_F_3) which caused problem to plot the PCoA with `check_pcr_repl` function as R will automatically add an X before rownames starting with numbers (i.e., X05_R_F_3). 

This caused the function to fail (line 41:43)
![image](https://user-images.githubusercontent.com/49724216/212744453-7e40953b-4f97-46a2-9085-7479cd703309.png)

I found a workaround removing the X in rownames by modifying locally the function using ``` rownames(d) <- gsub("X","",rownames(d))```  between lines 31 and 32 (not clean but efficient in my case; having no X in my sample names).

This really is a minor issue but I think it might be nice to fix it or at least mention in the "data format and structure" section of the [metabaR tutorial](https://metabarfactory.github.io/metabaR/articles/metabaRF-vignette.html#data-format-and-structure) that sample names should not start with digits (which is, as I am learning, a bad habit in general).

Thank you again!
Cheers,
Tristan.

**Comment by lionncle** [comment]
Hi,
Can you send us a rds file of your data or a part of your data so that we can reproduce the bug and try to correct it. 

I think that the problem comes from the data.frame function which should generate automatically these X in the colnames and rownames. To avoid this we can add the tags check.names and check.rows and pass them to false but it's dangerous to do that because in this case the column and row names are not checked anymore and many errors like duplicates can happen. If this is the case we will not be able to modify the code. 

Cheers,
Clément

**Comment by LafontRapnouilTristan** [comment]
Hi Clément,

I'll send you part of my data.
These are incomplete data I use for your package testing so weird results but should do the trick to test this problem!

The `.zip` contains two `.rds` files, one "bug" that allow you to reproduce the bug and one "ok" which do not cause the bug while having digits starting sample names.

[metabar_issue_50.zip](https://github.com/metabaRfactory/metabaR/files/10435088/metabar_issue_50.zip)

Each `.rds` contains 2 metabarlists, "raw_data" corresponding to the list before cleaning and "clean_data" after cleaning steps. 

There's not much differences as, again, these are not complete data with controls and all.

This second file has control starting with letters but as we remove them they're not an issue.

Don't run the "control removing" step and it bugs again.

It seems that having only digits starting names do not trigger the problem but I don't have time to investigate much more...

Adding `rownames(d) <- gsub("^X","",rownames(d)) ` fixed it for me as indicated above and I'll go with that.

Here is the code to reproduce the problem:

```
library(metabaR)
library(cowplot)
library(ggplot2)

load("ok.rda")
load("bug.rda")

###### Buggy ######  


# Get row data only for samples
tmp <- subset_metabarlist(raw_data_bug, table = "pcrs",
                          indices = raw_data_bug$pcrs$type == "sample")

# Build PCoA ordinations 
mds1 <- check_pcr_repl(tmp,
             groups =  as.factor(tmp$samples$organ))
mds2 <- check_pcr_repl(clean_data_bug,
             groups =  as.factor(clean_data_bug$samples$organ))

```

Solving this requires a modified function such as:

```
test_check <- function (metabarlist, replicates = NULL, groups = NULL, funcpcr = NULL) 
{
  if (suppressWarnings(check_metabarlist(metabarlist))) {
    reads <- metabarlist$reads
    if (is.null(replicates)) {
      replicates <- metabarlist$pcrs$sample_id
    }
    if (length(replicates) != nrow(metabarlist$reads)) {
      stop("`replicates` length should be equal to the number of rows of table `reads`")
    }
    if (is.null(groups)) {
      stop("groups should be defined")
    }
    if (length(groups) != nrow(metabarlist$reads)) {
      stop("`groups` length should be equal to the number of rows of table `reads`")
    }
    if (!is.null(funcpcr)) {
      if (length(funcpcr) != nrow(metabarlist$reads)) {
        stop("`funcpcr` length should be equal to the number of rows of table `reads`")
      }
      if (!is.logical(funcpcr)) {
        stop("`funcpcr` should be logical")
      }
      funcpcr <- ifelse(funcpcr, "0ok", "dyspcr")
    }
    reads_stdt <- reads/rowSums(reads)
    bar <- rowsum(reads_stdt, replicates)/as.vector(table(replicates))
    all <- rbind(reads_stdt, bar)
    all.d <- vegdist(all, "bray")
    mds <- cmdscale(all.d, k = 2, eig = T, add = T)
    d <- data.frame(mds$points)
############ ADDED LINE
    rownames(d) <- gsub("^X","",rownames(d))
############  ADDED LINE  
    d$points <- ifelse(rownames(d) %in% rownames(bar), "bary", 
                       "samp")
    d.new <- data.frame(d[d$points == "samp", ])
    d.new$replicates <- replicates[match(rownames(d.new), 
                                         rownames(reads))]
    d.new$bary_x <- d$X1[match(d.new$replicates, rownames(d))]
    d.new$bary_y <- d$X2[match(d.new$replicates, rownames(d))]
    d.new$groups <- 0
    d.new$funcpcr <- "0ok"

    if (!is.null(groups)) {
      d.new$groups = groups
    }
    if (!is.null(funcpcr)) {
      d.new$funcpcr = funcpcr
    }
    ggplot(d.new, aes(x = .data$X1, y = .data$X2, color = .data$groups)) + 
      geom_point(aes(shape = funcpcr)) + theme_bw() + 
      scale_shape_manual(values = c(19, 8), labels = c("good", 
                                                       "bad")) + geom_segment(aes(x = .data$bary_x, 
                                                                                  y = .data$bary_y, xend = .data$X1, yend = .data$X2), 
                                                                              color = "grey") + 
      labs(x = paste("PCoA1 (", round(100 * mds$eig[1]/sum(mds$eig), 2), "%)", sep = ""),
           y = paste("PCoA2 (", round(100 * mds$eig[2]/sum(mds$eig), 2), "%)", sep = ""),
           shape = "PCR type")
  }
}
```


With the "ok" dataset the function `check_pcr_repl` works fine despite have digit starting sample names. 

I assume as mentioned above that removing the letter starting names of controls remove the "conflict".

```
###### Working ######  

# Get row data only for samples
tmp <- subset_metabarlist(raw_data_ok, table = "pcrs",
                          indices = raw_data_ok$pcrs$type == "sample")

# Build PCoA ordinations 
mds1 <- test_check(tmp,
                   groups =  as.factor(tmp$samples$organ))
mds2 <- test_check(clean_data_ok,
                   groups =  as.factor(clean_data_ok$samples$organ))

```
Note that plotting the PCoA in this case we'll return a warning because I don't have any pcrs replicates so no segment can be drawn and thus the `geom_segment` of the function returns :  `removed XXX rows containing missing values `. 

```

# Custom colors
a <- mds1 + labs(color = "organ") +
  theme(legend.position = "none") + 
  ggtitle("Raw data")
b <- mds2 + labs(color = "organ") +
  ggtitle("Clean data")

# Assemble plots
leg <- get_legend(b + guides(shape=F) + 
                    theme(legend.position = "right", 
                          legend.direction = "vertical"))
ggdraw() +
  draw_plot(a, x=0, y=0, width = 0.4, height = 1) + 
  draw_plot(b + guides(color=F, shape=F), x=0.42, y=0, width = 0.4, height = 1) +
  draw_grob(leg, x=0.4, y=0)   

```
Hope you have everything that you need and tell me if not!!

As said I can't spend much more time on this and my workaround works fine in my case.

If as you feared you can't fix this in a clean way I suggest that you mention it in the tutorial, it is not a lot of work to add a letter in front of our samples names anyway ;)  !!

Thanks again for your great work and have a nice day!!
Cheers,
Tristan

**Comment by lionncle** [comment]
Hi,

So, I played with your data and indeed an error occurs with the "bug" data. I would have preferred to use the same data for the "bug" and "ok", the comparison would have been easier. 
It would have been better if you had sent me the real error message, it would have made my task easier because the error does not come from the renaming of the rownames with "X" but from the fact that R tries to add a vector which is not of the same size as the data.frame, in this case it adds the vector "groups" to the data.frame d.new which is a data.frame containing only the information of the samples (without the barycenters calculated above). This difference in size is due to the fact that the barycenters of the replicates not renamed with the "X" are well detected as barycenters but not the others which were renamed and thus the data.frame is no longer 2 times the size of the vector which is added. This means that the "ok" data is not good because all calculated barycenters are considered as replicates. The error comes rather from the fact that you use the function without replicates and therefore the barycenters have the same names as replicates.

This leads me to ask you why you use check_pcr_rpl? because in your case it is useless because you have no pcrs replicates (all your sample_id are unique). If you still want to make the graph I invite you to use the replicates parameter which must contain the groups of replicates to generate the barycenters and therefore which corresponds to the names of the barycenters and in this case the bug will be avoided (of course you must rename the names that begin with a number to avoid the side effects of the renaming done by the data.frame). So there is no bug in the code. 

Moreover for information, it is not rds that you sent me but rda (https://stat.ethz.ch/R-manual/R-devel/library/base/html/readRDS.html, https://stackoverflow.com/questions/21370132/what-are-the-main-differences-between-r-data-files).


Translated with www.DeepL.com/Translator (free version)

Cheers,
Clément

**Comment by LafontRapnouilTristan** [comment]
Hi,

First i'd like to apologize for not having provided the best data and information for testing.
I am new to "bug reporting" and don't have the best practices, I'll sure do better next time!

My usage of the function is part of an exploration of the package for future usage with other data that might have replicates and I was just trying around to understand how it worked even if it did not make any biological/scientific sens.

Using the replicates parameter as "groups" works fine without having to rename the samples.

My bad for the rds/rda, I figured that I needed more than one object so gave you rda but didn't change my comment accordingly. 
Moreover, I guess a list in rda would have work as well.

Again, thanks for your time and answers!

Cheers,
Tristan

Closed issue indeed!

**Comment by lionncle** [comment]
I'm sorry if my message seemed aggressive, it wasn't intended to be, but it's quite annoying to spend time on a bug that doesn't actually exist because it's due to a misuse of the function, and that you're proposing a solution that isn't good. I don't have much time to spend on maintaining the package either.

For bug reporting it is important to give only the essential and not a lot of data, 3/4 of which is useless. In your case, you would have sent me 2 rds ("bug" and "ok") with the same common sample names and for the bug the names not starting with digits that would have been perfect. 

You should also keep in mind that when you submit an issue, the person looking at it assumes that the user is using the code correctly and that the error is really in the code. 

Also, before you propose a solution to the bug, try to understand the code so that you can then provide the solution and check that it works. In your case for example you have a result but if you run line by line the code you will realise that this result is not good because the barycentres have the same names as the replicates which is not good because when we try to identify the barycentres and the replicates we only detect replicates (side effect of the renaming of the rownames of the data.frame with the digits) and so what follows will treat the barycentres as replicates, which is not good. 

For information replicates and groups are two very different parameters. The first one allows to generate the barycentres of the different pcrs replicates. The second allows you to colour the projected points to improve the interpretation of the graphics. In your case, if you don't have any pcrs replicates, either you create them using for example the metadata of the samples or you don't use the function. If you only want to have a projection use the cmdscale and ggplot functions. Using functions that have been diverted from their intended purpose is never good and exposes you to unintended side effects. 

Again, just because a function gives an error-free result does not mean that the result is correct. 

To test the package, use instead the data in the thumbnail that allows you to actually test the functions. You have several data sets in this directory: https://github.com/metabaRfactory/metabaR_external_data

Thanks anyway for your interest in our package.

Bonne continuation,
Clément Lionnet
